export const ADD_SERVICE = 'ADD_SERVICE'
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS'
export const ADD_SERVICE_FAILURE = 'ADD_SERVICE_FAILURE'
export const GET_SERVICES = "GET_SERVICES"
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS"
export const GET_SERVICES_FAILURE = "GET_SERVICES_FAILURE"